/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ericwchin.liferay.pwa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BrowserSubscription service. Represents a row in the &quot;PWA_BrowserSubscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ericwchin.liferay.pwa.model.impl.BrowserSubscriptionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ericwchin.liferay.pwa.model.impl.BrowserSubscriptionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrowserSubscription
 * @generated
 */
@ProviderType
public interface BrowserSubscriptionModel
	extends BaseModel<BrowserSubscription>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a browser subscription model instance should use the {@link BrowserSubscription} interface instead.
	 */

	/**
	 * Returns the primary key of this browser subscription.
	 *
	 * @return the primary key of this browser subscription
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this browser subscription.
	 *
	 * @param primaryKey the primary key of this browser subscription
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the browser subscription ID of this browser subscription.
	 *
	 * @return the browser subscription ID of this browser subscription
	 */
	public long getBrowserSubscriptionId();

	/**
	 * Sets the browser subscription ID of this browser subscription.
	 *
	 * @param browserSubscriptionId the browser subscription ID of this browser subscription
	 */
	public void setBrowserSubscriptionId(long browserSubscriptionId);

	/**
	 * Returns the group ID of this browser subscription.
	 *
	 * @return the group ID of this browser subscription
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this browser subscription.
	 *
	 * @param groupId the group ID of this browser subscription
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this browser subscription.
	 *
	 * @return the company ID of this browser subscription
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this browser subscription.
	 *
	 * @param companyId the company ID of this browser subscription
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this browser subscription.
	 *
	 * @return the user ID of this browser subscription
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this browser subscription.
	 *
	 * @param userId the user ID of this browser subscription
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this browser subscription.
	 *
	 * @return the user uuid of this browser subscription
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this browser subscription.
	 *
	 * @param userUuid the user uuid of this browser subscription
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this browser subscription.
	 *
	 * @return the user name of this browser subscription
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this browser subscription.
	 *
	 * @param userName the user name of this browser subscription
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this browser subscription.
	 *
	 * @return the create date of this browser subscription
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this browser subscription.
	 *
	 * @param createDate the create date of this browser subscription
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this browser subscription.
	 *
	 * @return the modified date of this browser subscription
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this browser subscription.
	 *
	 * @param modifiedDate the modified date of this browser subscription
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the endpoint of this browser subscription.
	 *
	 * @return the endpoint of this browser subscription
	 */
	@AutoEscape
	public String getEndpoint();

	/**
	 * Sets the endpoint of this browser subscription.
	 *
	 * @param endpoint the endpoint of this browser subscription
	 */
	public void setEndpoint(String endpoint);

	/**
	 * Returns the auth of this browser subscription.
	 *
	 * @return the auth of this browser subscription
	 */
	@AutoEscape
	public String getAuth();

	/**
	 * Sets the auth of this browser subscription.
	 *
	 * @param auth the auth of this browser subscription
	 */
	public void setAuth(String auth);

	/**
	 * Returns the key of this browser subscription.
	 *
	 * @return the key of this browser subscription
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this browser subscription.
	 *
	 * @param key the key of this browser subscription
	 */
	public void setKey(String key);

}